### ISSUE TITLE
Change to use log-broker to write log messages

### ISSUE THREAD

**Issue by BLYKIM** [petabi/review-database#163]
Use aicers/log-broker to save log messages into Giganto

**Comment by msk** [comment]
The integration of a specific logging destination such as `aicers/log-broker` directly into `review-database` may not align with the design principles we have established for this crate. Let me explain why.

`review-database` is designed to be an abstract layer for data storage, with a core focus on being agnostic to the specifics of logging implementations. This design choice is intentional to ensure that `review-database` remains flexible and adaptable to various use cases and environments. By keeping the crate decoupled from specific logging destinations, we ensure that it can be seamlessly integrated into any Rust application, including REview, without imposing limitations or dependencies on particular logging tools or systems.

The responsibility of choosing and configuring the logging destination should ideally reside with the application using the crate, in this case, REview. This approach provides the following benefits:

1. **Flexibility**: Applications can choose a logging destination that best fits their specific requirements and infrastructure, be it `aicers/log-broker` or any other logging system.
2. **Customizability**: Applications have the freedom to customize their logging strategy, formats, and levels, tailored to their specific needs and contexts.

Since `review-database` uses the [`tracing`](https://docs.rs/tracing/latest/tracing/) crate for logging, the application (REview) just needs to implement a new `tracing` subscriber to direct logs to `aicers/log-broker`. Implementing a subscriber using the traits from `tracing-subscriber` is a straightforward process. For reference, the subscriber currently used in REview, defined in [`tracing_subscriber::fmt`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/), can serve as a great example of how to implement a subscriber. This allows for greater flexibility and customization in how logging is handled, without tying `review-database` to a specific logging backend.

That said, I am always open to exploring ways to enhance `review-database`. If you believe there are significant advantages or compelling reasons to integrate `aicers/log-broker` directly into `review-database`, I would love to hear more about your perspective. Could you please share any specific benefits or use cases where having `aicers/log-broker` integrated at the crate level would provide a clear advantage over the current approach?

**Comment by BLYKIM** [comment]
@syncpark @sophie-cluml 의견 부탁드립니다

**Comment by msk** [comment]
@sophie-cluml,

Thanks for weighing in on this topic. Your queries help clarify the direction we should take. Let me address each point:

> * `review-database` still uses `tracing` (cancel the currently opened PR).

That's correct. The proposed changes in #165 suggest a modification to the handling of log messages based on severity. `review-database`'s current implementation using `tracing` adequately captures and forwards all necessary information. I'd be interested to know if there are specific functionalities or advantages that `log-broker` provides which `tracing` cannot within the context of `review-database`.

> * `review` uses `log-broker`, instead of `tracing`

The term "using" needs a bit more specificity. My vision is that REview should continue emitting log messages through `tracing`, with `log-broker` being implemented as a [`Subscriber`](https://docs.rs/tracing/latest/tracing/trait.Subscriber.html). This way, `log-broker` becomes an intermediary, processing and forwarding log messages as needed, without replacing `tracing`. Essentially, `log-broker` would work as a custom `Subscriber` within the `tracing` ecosystem.

> * Specify whether logs from `review-database` should be written to files only or also transferred to redis when `review` uses `log-broker`

This decision falls squarely within the remit of the `Subscriber` that `log-broker` implements. Adhering to the `tracing` framework's design principles, `log-broker` should handle the specifics of whether logs are written to files, sent to Redis, or any other sink. `review-database` remains agnostic to these implementations, maintaining its focus on data storage abstraction.

Given this understanding, I believe that `review-database` should continue using `tracing` without modification. Therefore, we can close the current issue on `review-database` and shift this discussion to the REview repository to focus on the integration and implementation of `log-broker` as a `tracing` `Subscriber`.

**Comment by sophie-cluml** [comment]
Hello. Thank you for feedback! I see the benefits of `log-broker` over `tracing` as follows.
- Developers can easily choose the output target destination for at the time of calling log macros, from one of three choices
  - 1) Only to the destination used when setting up `tracing`.
  - 2) Only to redis
  - 3) To both

Meanwhile, implementing `Subscribe` does not allow specifying the output destination for each log, since logs in their simplest forms like `info!("info log")` do not carry the information. It would be necessary to provide the information with something like `span`, which requires developers calling the log macro to `enter` into `span` and `drop` it. This would increase the complexity of calling log macros for the individual developers, while specifying `LogLocation` is relatively easier.

Implementing a `Layer` was considered in the beginning, but what I found upon my survey was that it still does not lift up the burden to utilize something like `span`.

Alternate way considered was to remove `tracing` dependency from `log-broker` and have `log-broker` provide an API (or macro) that allows `log-broker` to be responsible only for sending values to redis. This way, individual developers can call the macro of `tracing` when they want to log, call the API (or macro) of `log-broker` when they want to send values to redis, and call each separately when they want to do both.

This was discussed with Sehkone in the planning phase of `log-broker`, but there could be better ways that we did not see at that moment. So I would love to listen to your suggestions. 
One problem is that I cannot access `REview` repository, so it would be great to continue the discussion in the `log-broker` or else where you find appropriate. 

Besides, another idea came up recently was to change to build `log-broker` as an executable binary, and make it read the log files generated by applications and send the logs to redis. This way, decoupling would be achieved but other concerns would arise, such as 1) sending logs only to redis would not be viable, 2) complexity of deployment and operation would increase.

**Comment by sophie-cluml** [comment]
I am afraid my previous comment (I just deleted it) might have caused confusion, so let me clarify. I agree to using `Subscriber`, which I also had looked into.

One caveat of using `Subscriber` is that if we use it, to let developers choose which destination user wants to send the logs to, developers will be calling `span!` and drop repeatedly. To make this more convenient, we can make macros in review. Which do you think is better?

**Comment by msk** [comment]
@sophie-cluml,

I understand your point about the convenience of directing logs to specific destinations and the potential use of macros or functions in REview. However, I believe our perspectives on this issue differ fundamentally.

From what I gather, you are suggesting an approach where developers explicitly choose the log destination at the time of logging, like `log(REDIS, "this message must go to Redis")`. My stance, however, leans towards a more conventional method where the log's severity itself is the primary determinant at the logging stage, as in `log(WARN, "this is a warning")`,

The use of severity levels as a sorting mechanism for logs is a long-established practice in software development. Deviating from this convention to allow for destination-specific logging at the library level raises several concerns. Firstly, it would require developers of `review-database` and similar libraries to be aware of the specific log destinations used in each application, which is not practical, especially as the number of applications using the library potentially grows. Secondly, it places an additional cognitive burden on developers to understand the context of each API call within `review-database` to make appropriate decisions about log destinations. This goes against the principle of decoupling and could unnecessarily complicate the development process.

However, I am open to understanding the specific use cases or necessities that might warrant adopting an API like `log(REDIS, "this is a warning")`, despite these drawbacks. If there are compelling scenarios where such an approach is essential, I would be interested in discussing them further.

If there are no strong use case for this approach, I propose letting the application developer specify log destinations corresponding to severity levels when initializing the `Subscriber`. For instance, when REview creates a `Subscriber` instance, it could configure that all `info` and higher severity messages go to Redis, while others are directed to stdout. This way, other library crates like `review-database` and `review-web` can continue using macros like `info`, `warn`, etc., to indicate severity only, adhering to the established logging conventions and ensuring a clear separation of concerns.

**Comment by sehkone** [comment]
@msk

**Comment by sehkone** [comment]
@msk 

I'd like to discuss our logging system in detail, highlighting all the concerns and aspects I have in mind. I will outline as many issues as possible for clarity.

**Core Features Needed:**
1. We need to store all audit logs, and some standard system logs, on a central log server for an extended period, like three years. These logs should be accessible and searchable through our user interface.
2. The primary distinction between audit logs and standard logs is their focus on security-related matters.
3. Decisions about which standard logs to handle in this manner should be made by our team, not users, meaning these choices can be implemented directly in our code.

**Additional Features Requested by a Client:**
1. We should also process logs from external systems, not just our own, in the same manner.
2. Although we can't access these external systems directly, we can arrange for the client to transfer their logs to us in a specified manner, such as using Redis.

**Log-broker Overview:**
The Log-broker was initially developed to address these additional features. It handles logs from external ones, channeling them through Redis, from which Giganto retrieves them. However, we reached to the point where we can use this to handle our own logs as well to avoid dual ways of management logs. We understand that this isn't the most conventional or optimal approach, but it looked quite good to us under our limited resources and timeframe.

**Your Perspectives and Design Suggestions:**
However, I completely agree with your viewpoints and would like your input on a few key design questions:

1. Should we process our own audit logs and standard logs in the same manner?
2. Is Giganto a suitable choice for central log storage? If so, how should Giganto acquire our logs?
3. Considering the current setup where logs from other systems are sent to Redis, how should Giganto access these logs?

I would really appreciate it if you could design a system that takes these into account.

**Comment by sehkone** [comment]
@msk, @sophie-cluml, and @BLYKIM 

I am closing this issue and opened [a new discussion](https://github.com/aicers/review-web/discussions/105)
