### ISSUE TITLE
Migrate `qualifier` table from PostgreSQL to RocksDB

### ISSUE THREAD

**Issue by msk** [petabi/review-database#171]
The `qualifier` table in the current PostgreSQL database maintains a simple structure with only two columns: an integer ID and a text field for the category name. Considering this simplicity, migrating this table to a Key-Value Store such as RocksDB seems more suitable.

As a part of this issue, it is suggested to perform the following steps:

1. A migration function should be designed and implemented within the `migration` module. This function should aim to migrate all existing data from the `qualifier` table in PostgreSQL to a new RocksDB column family.
2. A new service layer needs to be implemented to handle CRUD operations with `IndexedMap`.
3. Testing of the migration function is necessary to ensure data integrity and the effectiveness of new CRUD operations.

**Comment by minshao** [comment]
@syncpark After reviewing the current code base, I came to the impression that the `status_id` and `qualifier_id` for a certain cluster evolve as the following:
1. when a cluster is created:
  * `status_id` default to `disabled`, for flagged cluster it will be set to `pending review`,
  * `qualifier_id` default to `unknown`
2. when user **change** the `qualifier_id` value of a certain cluster during cluster update process,
  * `qualifier_id` will be set to the value user updated.
  * `status_id` will change to `reviewed`.
  * 
**Could you confirm 1. and 2. for me and let me know if there are other additional settings or behaviors for `status_id` and `qualifier_id`?**

Besides, there are a few questions that arises:
a. 2. is triggered by PostgreSQL and will be enforced after `update` routine which means that it will overwrite the `status_id` that designated by the user during `update`. To clarify:
  * suppose user send a request through web UI: 
```GraphQL
  mutation {
  updateCluster(id: 7343, status: 2, qualifier: 4)
}
```
  * Below will be achieved in the database, notice that `status_id` will be 1 after the update instead of 2 as requested. 
```Json
        {
          "node": {
            "id": "7343",
            "status": {
              "id": "1",
              "description": "reviewed"
            },
            "qualifier": {
              "id": "4",
              "description": "mixed"
            }
          }
        },
```
  * **Could you confirm whether such behavior is intentional and preferred?**

**Comment by minshao** [comment]
@syncpark I've created a bug report for this, could you share your opinion on this? It would be great to know how the user end would like it to be designed.

**Comment by syncpark** [comment]
@minshao Sorry for late reply.

* Your opinions 1. and 2. are right. No other opinions for this two.
* But for the last comment, there can be two cases to set `status`.

#### Case 1. The users of Web UI can modify the `status`
Users will review the clustering result, then modify the `status and qualifier`. This modification can be the last or the user can hand over to other user to review the cluster in detail. Or Another user can `overwrite` the `status and qualifier` later.
* As a result, for the request from the Web UI like this:
```GraphQL
  mutation {
    updateCluster(id: 7343, status: 2, qualifier: 4)
  }
```
* I think the database should be:
```Json
        {
          "node": {
            "id": "7343",
            "status": {
              "id": "2",
              "description": "pending review"
            },
            "qualifier": {
              "id": "4",
              "description": "mixed"
            }
          }
        },
```
I believe that databases should follow the user's intent.

#### Case 2. `REconverge` or `Triage agent`(currently under development) can set the status.
`REconverge` or `Triage agent` can set the status of cluster to `pending review` when the cluster is classified as `suspicious`. I don't think that `REconverge` or `Triage agent` can set the status to `disabled` or `reviewed`. Only `pending review` can be possible.

* If the `status` of a cluster is `disabled`, then `REconverge` or `Triage agent` can modify it to `pending review`.
* If the `status` is `reviewed`, then `REconverge` or `Triage agent` can not modify the `status` any more because the status `reviewed` is modified by the user.

As a result, I think that `REconverge` or `Triage agent` can only modify the status from `disabled` to `pending review`.

**Comment by syncpark** [comment]
@msk @sehkone @MW-Kim
Please read above opinions and leave comments.

**Comment by sehkone** [comment]
@syncpark, from REview's perspective, REview just accepts as a GraphQL API request that REconverge or else wants to change the status? I mean it's not necessary to consider Case 2.

**Comment by syncpark** [comment]
@sehkone Currently REconverge sends `UpdateClusterRequest` including `status_id = 'pending review'` for the suspicious candidate clusters. The REview code may be modified depending on the results of this discussion.

Because REview just overwrite the `status_id` with the value from the REconverge, the status `reviewed` can be overwritten.
I think the code should be modified to overwrite the `status_id` only when it's value is `disabled`.

**Comment by sehkone** [comment]
@syncpark, thank you for clarification on the matter of REconverge.

**Comment by sehkone** [comment]
What @syncpark is saying about "triage agent" has the following idea behind:

Users usually want to filter suspicious events which are detected by REconverge so that they can focus on small number of events. We call the filtering of events "triage". Triage sometimes depends on 3rd parties' DB containing useful information on harmful IPs, URLs, or patterns, and looking up them might cost users money or time. So, we cannot update the triage result to REview at the same time when events are detected. A triage agent will take the role of filtering events based on a variety of information outside or custom logic set by users and what it does is periodically done. What it exactly should do must be discussed later, but some features one of our clients asked are now under development for that matter only.

**Comment by syncpark** [comment]
@sehkone @MW-Kim I need a discussion in detail for the `Triage agent` case. Recently we had discussed to choose the connection protocol  between `REview` and `Triage agent`,  QUIC or GraphQL.

If the `Triage agent` simply scores the clusters or events and it does not have classification role, then you're right, the Case 2 is unnecessary for the `Triage agent`.

**Comment by sehkone** [comment]
> @sehkone @MW-Kim I need a discussion in detail for the `Triage agent` case. Recently we had discussed to choose the connection protocol between `REview` and `Triage agent`, QUIC or GraphQL. But no conclusion yet.
> 
> If the `Triage agent` simply scores the clusters or events and it does not have classification role, then you're right, the Case 2 is unnecessary for the `Triage agent`.

We will discuss this later not here.

**Comment by sehkone** [comment]
@minshao
Do you need any more information from @syncpark or me to go on? If so, please let us know.

**Comment by minshao** [comment]
> @minshao Do you need any more information from @syncpark or me to go on? If so, please let us know.

I'm good for now~ Thanks for the help. The changes have been reflected in review-database.

**Comment by sehkone** [comment]
> > @minshao Do you need any more information from @syncpark or me to go on? If so, please let us know.
> 
> I'm good for now~ Thanks for the help. The changes have been reflected in review-database.
@minshao,
Do you mean this issue has gotten done?

**Comment by minshao** [comment]
> > > @minshao Do you need any more information from @syncpark or me to go on? If so, please let us know.
> > 
> > 
> > I'm good for now~ Thanks for the help. The changes have been reflected in review-database.
> 
> @minshao, Do you mean this issue has gotten done? It looks done to me, so I merged the pending PR in review-web.

For the work in review-database, yes. But I think we need to move the discussion about the access right for status_id to review-web or review, depending on you guys' preference.
