### ISSUE TITLE
Improve flexibility of fields related to sensors in Node related struct

### ISSUE THREAD

**Issue by sophie-cluml** [petabi/review-database#283]
`tables::node::Settings` has below fields to represent some of sensor's configurations.

```rust
    http: bool,
    office: bool,
    exe: bool,
    pdf: bool,
    html: bool,
    txt: bool,
```

There are two problems with current implementation. 
- These are all `bool` in type, which means whenever we want to modify the sensor's configurations, we need to modify review-web.  
- These fields look like they are independent configurations, but there is dependency and hierarchy. , `office`, `exe`, `pdf`, `html`, `txt` belong to `http`.

I suggest to change the above fields like below:

```rust
  // this can currently have `office`, `exe`, `pdf`, `html`, `txt`, but more can be added in the future
  http_extract_options: Option<Vec<String>>,  
```

This is in line with review-web's issue: https://github.com/aicers/review-web/issues/228

**Comment by minshao** [comment]
Regarding the proposal, the current long-term plan involves storing the settings struct as a toml formatted string into the database. This approach offers flexibility for individual App instances, i.e. *Agent* or *Review-client*, to define, update, or migrate their own settings or configurations.

However, I would like to express my objection to the proposed change for the following reasons:

* The `http_extract_options: Option<Vec<String>>` field poses concerns regarding error-prone string parsing issues. Moreover, the use of `Option` seems redundant here since an empty vector could adequately represent the same concept. Therefore, an alternative approach like the following could be considered if a single field is preferred:
```Rust
enum Extraction {
    Http,
    Office,
    Exe,
    ...
}
...
extractions: Vec<Extraction>
 ```
* If the `Extraction` is not going to change much, I do find the current fields to be *toml* friendly.

**Comment by sophie-cluml** [comment]
Thank you for an alternative and sharing future plans.  Also, `Option` seems redundant, thanks for pointing it out.
Using enum seems good too. But I am afraid if vector of `Extraction`, where `Extraction` has `Http` as its variant, may not be able to show the hierarchy or relationship that `http` has with `office`, `exe`, `pdf`, `html`, `txt`. But I am not sure if you  wanted to say that `Http` should to be variant of `Extraction`, or instead, you probably wanted to show me your idea with code snippet (which is so kind of you thank you). Anyway I agree with your idea in general, so let me close this issue.
