### ISSUE TITLE
Remove `html` from Node's `Settings` struct;  Add `vbs` field

### ISSUE THREAD

**Issue by sophie-cluml** [petabi/review-database#287]
Currently there are 5 fields that represent file types for sensor module in the Node related `Settings` struct: `office`, `exe`, `pdf`, `html`, and `txt`.
But the sensor module actually needs `office`, `exe`, `pdf`, `txt`, and `vbs`. 

So, I propose below:
- Remove `html` field, and incorporate the value of the field with `txt` after migration
  - That is, if `html` **OR** `txt` in the past were `true`, new `txt` field is migrated as `true`
- Add `vbs` field
  - Default value to use is `false`

**Comment by minshao** [comment]
@sophie-cluml 
* For existing sensors, is `Settings::html` valid, i.e. there exists some sensor that satisfies `html == true && txt == false`? Or is the `html == false` true all the time? Or `html == true && txt == true` could happen as well?

* Could you also explain to me the meaning of `office`, `exe`, `pdf`, `html`, and `txt`? For instance, are they flags indicating whether a sensor support a certain type of file? For another, could a sensor have multiple of them being true at the same time? I'm asking because I'm working on refactoring the current code and find it quite confusing. Thanks.

**Comment by sophie-cluml** [comment]
Hello minshao,

For your first question, `html` and `txt` should have never existed at the same time in this review-database as separate settings in the first palce, because they mean the same thing for the sensor module. We need to remove one of them, and sensor module prefers the name `txt` over `html`. So that is why `txt` is chosen to be left, and `html` to be removed.

For your second question, sensor module uses the fields like this:
```
# CASE 1
log_options = ["eml", "ftp", "http"]

# CASE 2 : with the full list of types
log_options = ["eml", "ftp", { option = "http", types = ["office", "exe", "pdf", "vbs", "txt"] }]
```
By the way, the term `log_options` is a bit misleading. What it truly means is "dump_options".  It is not related to logging with tracing library. (The term will be changed in the sensor module as an improvement soon.) 

And specifying "office", "exe", "pdf", "vbs", "txt" in the configuration mean that the sensor module will dump "office", "exe", "pdf", "vbs", "txt" related MIME types. If those are not specified in the `types` array, they will be filtered out.


Now going back to your first question, please note that there is no `html` in the `types` array. That's why we need to remove it. And the reason we want to migrate the value like below, is because we prefer to fix the previously wrong duplicate settings in a safer way. It is safer to have `txt` set to `true`, when `html` was `true` and `txt` was `false`.
```
after_migration_setting.txt  = before_migration_setting.html || before_migration_setting.txt
```
