### ISSUE TITLE
Move EventCategory definition to review-protocol crate

### ISSUE THREAD

**Issue by syncpark** [petabi/review-database#304]
https://github.com/petabi/review-database/blob/c52ee92e4393026cfd5fcbfaa9edab88795cf0d9/src/types.rs#L44-L55

We've decided to assign EventCategory to the detected events when they are created.
To share the EventCategory definition between server and client(analyzer), the definition must be moved to `review-protocol` crate.

- [x] Move `EventCategory` definition to `review-protocol` crate
- [x] Remove the `HttpThreat` member from the EventCategory
- [x] Modify related code

**Comment by syncpark** [comment]
@msk
Is it ok to move the EventCategory to review-protocol crate? 
I want to share the EventCategory definition between client and servers via review-protocol crate.

**Comment by msk** [comment]
@syncpark,

Yes, it's fine to move the `EventCategory` definition to the `review-protocol` crate. This makes sense for sharing the definition between client and server components.

Here are a couple of points to consider:

1. In `review-protocol`, we want to keep the `EventCategory` definition minimal, with only the essential `derive`s needed for protocol-level operations. This helps us minimize dependencies on other crates in `review-protocol`.

2. For `review-database`, we should create a separate `EventCategory` that wraps or maps to the one in `review-protocol`. This allows us to add any additional `derive`s or functionality needed for database operations without affecting the `review-protocol` definition.

This approach allows us to maintain a clean separation of concerns and minimize dependencies in `review-protocol` while giving `review-database` the flexibility it needs.

Regarding your specific tasks:

- Moving `EventCategory` to `review-protocol`: Approved. Please ensure you only include the minimal necessary `derive`s for protocol-level operations.
- Removing the `HttpThreat` member: If this is no longer needed, that's fine. Since we're already breaking backward compatibility, this removal shouldn't be an additional concern.

**Comment by msk** [comment]
> Can you explain how to do the enum wrapping?

Please see [Wrapping a remote enum](https://async-graphql.github.io/async-graphql/en/define_enum.html#wrapping-a-remote-enum).
